CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_passwords (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    hashed_pass VARCHAR(255) NOT NULL
);