name: Deploy VitePress and Marp
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build-vitepress:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm run docs:build
      - name: Upload VitePress Result
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vitepress-dist
          path: docs/.vitepress/dist

  build-marp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Marp Build
        run: |
          npx @marp-team/marp-cli --input-dir ./slides/ --theme-set ./slides/style.css --output marp-dist --html
          npx @marp-team/marp-cli --input-dir ./slides/ --theme-set ./slides/style.css --output marp-dist --pdf --allow-local-files

      - name: Copy Assets
        run: |
          rsync -av --exclude="*.md" ./slides/ marp-dist/

      - name: Upload Marp Result
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: marp-dist
          path: marp-dist

  deploy:
    needs: [build-vitepress, build-marp]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download VitePress
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: vitepress-dist
          path: final-dist

      - name: Download Marp
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: marp-dist
          path: final-dist/slides

      - name: Upload final artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: final-dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5