name: Deploy VitePress and Marp
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build-vitepress:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm run docs:build
      - name: Upload VitePress Result
        uses: actions/upload-artifact@v6
        with:
          name: vitepress-dist
          path: docs/.vitepress/dist

  build-marp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Marp Build
        run: |
          npx @marp-team/marp-cli --input-dir ./slides/ --theme-set ./slides/style.css --output marp-dist --extension html
        env:
          MARP_USER: root:root

      - name: Copy Assets
        run: |
          rsync -av --exclude="*.md" --exclude=".git/" ./slides/ marp-dist/

      - name: Upload Marp Result
        uses: actions/upload-artifact@v6
        with:
          name: marp-dist
          path: marp-dist

  deploy:
    needs: [build-vitepress, build-marp]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download VitePress
        uses: actions/download-artifact@v6
        with:
          name: vitepress-dist
          path: final-dist

      - name: Download Marp
        uses: actions/download-artifact@v6
        with:
          name: marp-dist
          path: final-dist/slides

      - name: Upload final artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: final-dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4